### ISSUE TITLE
阅读源码产生的疑惑

### ISSUE THREAD

**Issue by xiangtianyu** [zehuamama/balancer#16]
你好，我最近阅读项目源码的时候发现一个问题，Balancer.Balance方法照理来说应该是负载均衡器选择最终目标服务器的方法，但是只在ServeHTTP方法中被调用，且ServeHTTP方法只在maxAllowedMiddleware中被使用，也就是说如果此处配置文件中config.MaxAllowed配置为0，那么负载均衡器就无法使用
```
if config.MaxAllowed > 0 {
    router.Use(maxAllowedMiddleware(config.MaxAllowed))
}
```

请问下这个是不是一个bug？

**Comment by zehuamama** [comment]
不会啊，为0的时候这个中间件都不会插进去

**Comment by xiangtianyu** [comment]
> 不会啊，为0的时候这个中间件都不会插进去

那就是说这个值为0时，服务器不具备负载均衡的能力？

**Comment by zehuamama** [comment]
值为0不限流，怎么没有负载均衡的能力？

**Comment by xiangtianyu** [comment]
> 值为0不限流，怎么没有负载均衡的能力？

我迷惑了，因为在我的理解里面，负载均衡的实现是通过调用Balance方法，然后在这个方法中通过一定的算法来进行服务器选择。但是现在没有地方调用这个方法，那么是怎么实现负载均衡的呢？

**Comment by zehuamama** [comment]
他只是个中间件，为0的时候就是个正常的负载均衡器啊？那个中间件是限流的

**Comment by xiangtianyu** [comment]
可以加个微信私聊吗？
