### ISSUE TITLE
round-robin balancer has a thread-safety problem

### ISSUE THREAD

**Issue by biningo** [zehuamama/balancer#19]
Hi~ @zehuamama 
I found that round-robin balancer has a thread-safety problem, increasing the current index but the lock is read lock. This may cause the result we get from the round-robin balancer may not be what we want.

Reference: https://github.com/zehuamama/balancer/blob/6e8ef295bbbc76b6815d9f297b26352aeaf37fd4/balancer/round_robin.go#L35C5-L35C5

**Comment by biningo** [comment]
I think could use the Go atomic package  to slove this ploblem.

**Comment by zehuamama** [comment]
> I think could use the Go atomic package to slove this ploblem.

嗯，非常感谢，我疏忽这个问题，支持使用原子命令，你可以提个 pr，我帮你合入
